version: '3.9'
services:
       web:
          build: 
            context: ./web
          ports:
            - 80:80
          volumes:
            - ./web/myhtmlcode:/usr/share/nginx/html/
          networks:
             - webnet
       app:
        build:
         context: ./app
        ports:
         - 9000
        volumes:
          - ./app/myphpcode:/usr/share/nginx/html
        networks:
          - webnet
          - appnet

       db:
        build: 
          context: ./db
        ports:
         - 3306
        volumes:
          - databackup:/var/lib/sql
        networks:
           - appnet

   
networks:
  webnet:
    driver: bridge
  appnet:
    driver: bridge

volumes:
   databackup:
   
docker-compose install command 
  1 curl -SL https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
    2  chmod +x /usr/local/bin/docker-compose
    3  docker-compose -v

        
      
